#' sdbCheckContained
#'
#' Function checks for peak overlap between series in new_series tibble (annotated peak table) and series_db tibbles. If any peaks of a homologue_id in new_series is found in series_db, it's id is returned to prevent peak overlaps between series in seriesdb.
#'
#' Please note that peak matching is fuzzy, and depending on settings two peaks may or may not be considered overlapping. Matching stringency should be held similar over sdbCheckContained and annotateHomologues to avoid annotation overwriting caused by peak overlaps.
#'
#' @param seriesdb A seriesdb tibble created with createSeriesDB().
#' @param new_series Annotated series output generated by detectHomologues. By default, any homologue identifier equaling NA is omitted as this identifier is the default for non-series peaks.
#' @param ppm_tolerance Tolerance in ppm for matching two peaks.
#' @param rt_tolerance Retention time tolerance in matching. Beware of rt units in the database and peak table!
#'
#' @return A list of integer homologue identifiers that were found to be overlapping between new_series and seriesdb.
#' @export
sdbCheckContained <- function(seriesdb, new_series, ppm_tolerance, rt_tolerance){
  checkAnnotatedTableFormat(new_series)
  checkSeriesDBFormat(seriesdb)
  new_series <- filter(new_series, !(is.na(homologue_id)))
  matches <- mapply(checkAnyMatch, new_series$mz, new_series$rt, new_series$homologue_id,
                    MoreArgs = list(ppm_tolerance, rt_tolerance, seriesdb),
                    SIMPLIFY = TRUE) %>% na.omit(.) %>% unique()
  return(matches)
}
